# Use a base image. This example uses NGINX as a lightweight web server.
FROM nginx:alpine

# Copy your HTML, CSS, and JS files to the appropriate directory in the container
COPY . /usr/share/nginx/html

# Expose port 80 to allow external access
EXPOSE 80
